repos:
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
    - id: black
      language_version: python3

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.5.0
  hooks:
    - id: ruff
      args: ["--fix"]

- repo: https://github.com/myint/docformatter
  rev: v1.7.5
  hooks:
    - id: docformatter
      args: ["--in-place", "--wrap-summaries=88", "--wrap-descriptions=88"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: check-yaml 