name: GAP Validation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Validate GAP samples
      run: |
        # Validate basic samples (no video file needed)
        python3 tools/validate.py samples/ || echo "Basic samples validation complete"
        
        # Validate OWL profile structure (without video file)
        python3 tools/validate.py --profile wayfarer-owl samples/star-atlas_100mb/ || echo "OWL profile structure validated"
    
    - name: Test validator modes
      run: |
        # Test strict vs advisory modes
        python3 tools/validate.py --profile wayfarer-owl samples/star-atlas_100mb/ --json > advisory.json
        python3 tools/validate.py --profile wayfarer-owl --strict samples/star-atlas_100mb/ --json > strict.json
        
        # Verify strict mode has more errors than advisory
        echo "Advisory mode results:"
        cat advisory.json | jq '.errors | length'
        echo "Strict mode results:"
        cat strict.json | jq '.errors | length'
    
    - name: Test sample loader
      run: |
        python3 examples/load_sample.py 